from bokeh.models import Paragraph

# Descrição das alterações feitas no gráfico 7
texto_grafico_7 = Paragraph(text = "Escolhi fazer um gráfico de linha para representar a variação da expectativa de vida ao longo do tempo, do ano 2000 até o ano 2015. Para que a visualização ficasse mais completa, resolvi adicionar uma coluna com os continentes de cada país ao data frame e plotar a mudança da expectativa de vida média de todos os continentes ao mesmo tempo. O resultado foi uma visualização clara do aumento da expectativa ao longo dos anos.  Quanto à personalização, escolhi manualmente uma paleta de cores que considerei adequada para os continentes, com cores vibrantes que contrastam bem entre si. Optei por não alterar a cor de fundo para não diminuir o contraste e dificultar a visualização clara das linhas. Para isso, também aumentei um pouco a grossura das linhas. Nos eixos, alterei os ticks menores do eixo x e do eixo y para que só tenha um tick por ano, em ambos os casos. Modifiquei o grid para tornar visíveis as linhas dos ticks menores, mas aumentei um pouco a transparência e escolhi uma cor clara para não poluir muito a visualização e deixar o gráfico harmônico. Coloquei a legenda no canto inferior esquero pois achei que esse é o lugar onde ela menos atrapalha a visualização dos dados, mas ainda assim aumentei um pouco a transparência dela. Além disso, configurei a barra de ferramenta para esconder automaticamente e ocultar a logo do Bokeh. As ferramentas que eu disponibilizei foram: pan, zoom box, wheel zoom, reset e hover, porque achei que eram as mais relevantes para o gráfico em questão. Em especial, configurei a ferramenta hover, que utilizei para tornar o gráfico interativo, para exibir o ano e a expectativa de vida. Nos textos, utilizei a fonte Arial Black para destacar o título e a fonte Verdana para os eixos.")

# Descrição das alterações feitas no gráfico 8
texto_grafico_8 = Paragraph(text = "Para o segundo gráfico eu queria analisar mais profundamente a expectativa de vida através do tempo de um desses continentes. Escolhi a América do Sul e, para representar os dados, resolvi fazer um heatmap. Para isso, defini a cor mais clara como o menor valor (Bolívia, 62 anos), a cor mais escura como o maior valor (Chile, 85 anos), e um gradiente para representar qualquer valor entre esses dois. O resultado fornece uma visão geral bem clara da variação da expectativa de vida com relação aos países e ao tempo. Depois de diversos testes, defini que a paleta de cores Magma256 era a mais adequada para o heatmap porque as cores variam bastante, facilitando a visualização da diferença entre os valores, e ela é estéticamente agradável. Nos eixos, diminui um pouco o tamanho dos rótulos do eixo x para que eles não ficassem sobrepostos. Além disso, alterei os rótulos dos países Bolívia e Venezuela, pois os seus nomes na base de dados original eram: Bolivia (Plurinational State of) e Venezuela (Bolivarian Republic of), e esses títulos estavam apenas ocupando espaço e prejudicando a estética do gráfico. As ferramentas que eu disponibilizei foram: zoom box, wheel zoom, reset, save e hover, pois achei que eram as mais relevantes para esse tipo de gráfico. Resolvi não colocar o valor de cada retângulo no plot porque isso poluiria a visualização, então configurei a ferramenta hover para mostrar a expectativa de vida e o país. Além disso, também configurei a barra de ferramentas para esconder automaticamente e ocultar a logo do Bokeh. Como é um heatmap, não precisei alterar o fundo, o grid ou os ticks. Resolvi utilizar as mesmas fontes e dimensões nos 3 gráficos, para seguir um padrão e manter a identidade visual.")

# Descrição das alterações feitas no gráfico 9
texto_grafico_9 = Paragraph(text = "Ao analisar a correlação das variáveis da base de dados, percebi que as categorias escolaridade e composição de renda dos recursos (uma dimensão do IDH que avalia a distribuição de renda no país, sendo que a medida varia de 0 a 1, onde 0 indica alta desigualdade e 1 indica igualdade absoluta na distribuição de renda) possuíam uma das correlações mais altas (0.82). Por isso, resolvi fazer um gráfico de dispersão para analisar essa distribuição. Como os dados de todos os anos geram um gráfico muito confuso e amontuado, resolvi filtrar o data frame para o ano mais recente (2015). Para tornar a visualização mais rica, colori os pontos conforme o continente do país em questão. O resultado torna clara a relação entre os dois fatores (quanto maior a escolaridade, maior a distribuição de renda), e ainda permite observar tendências de cada continente. Resolvi adicionar um mecanismo interativo que permite ocultar os continentes desejados ao clicar na legenda para possibilitar um maior entendimento do gráfico, comparações entre continentes específicos ou análise de um só continente. Utilizei a mesma paleta de cores manual do primeiro gráfico. Novamente, modifiquei os ticks menores do eixo x para que ficasse um tick por ano, e acrescentei as linhas de grid desses ticks com uma transparência um pouco maior, linhas tracejadas e cor clara para não sobrecarregar a visualização e tirar o foco dos pontos. Configurei a barra de ferramentas para esconder automaticamente e ocultar a logo do Bokeh, pois não são elementos necessários, e utilizei as ferramentas pan, zoom box, wheel zoom, reset, save e hover, que são os mais relevantes nesse caso. Resolvi adicionar o país que o ponto representa no hover para analisar casos específicos, além da escolaridade e da distribuição de renda. Utilizei as mesmas dimensões e fontes dos outros dois gráficos, mudando apenas o tamanho do título para que se ajustasse com o gráfico.")


